### ISSUE TITLE
Typo in the Readme?

### ISSUE THREAD

**Issue by kevinsmith** [ericlbarnes/ci-minify#2]
The readme's example for minifying a CSS file reflect the usage for minifying JS instead.

Reads `$this->minify->js->min($file);` when it should read `$this->minify->css->min($file);`

**Comment by kevinsmith** [comment]
Thanks so much for this driver, by the way! I'll be pulling this into my project as soon as the current pull request is merged.

**Comment by ericlbarnes** [comment]
Now fixed and pull request is in too.
