### ISSUE TITLE
Unable to load the requested driver: Minify_js

### ISSUE THREAD

**Issue by maifith** [ericlbarnes/ci-minify#4]
I am getting this error, 

here is my code

```
$tmp = './_tmp/'.time().'.js';

write_file($tmp, $output); /* write the file into the file cache */

$contents = $this->minify->js->min($tmp);
$this->minify->save_file($contents, './_assets/_cache/building_coords.js');

$output = read_file('./_assets/_cache/building_coords.js');
```

We're building a Google Maps implimentation with CI2.  I just need it to be faster so we're minifying all JS and CSS.

**Comment by maifith** [comment]
Forgot to mention that I am first outputting the file, then compressing/minifying that file.  On subsequent calls to my json controller, I first check if the file exists.

**Comment by ericlbarnes** [comment]
What version of CodeIgniter are you using? Also using reactor or core?

**Comment by maifith** [comment]
Hey Eric, We're using 2.0.2 Reactor.

**Comment by maifith** [comment]
I should mention that this was indeed a bug, but I've since switched over to pack instead of minify.

Cheers
