### ISSUE TITLE
Minify and save a physical file more than one file

### ISSUE THREAD

**Issue by ghost** [ericlbarnes/ci-minify#8]
If I want to use an array of files to minify is not possible, it would be interesting to use as follows: 

$this->load->driver('minify');
$minify = $this->minify->css->min(array('css1.css','css2.css','css3.css'));
$this->minify->save_file($minify, './css/all.css');

ty

**Comment by ericlbarnes** [comment]
I'm no longer maintaining this project. I would recommend switching to Grunt or Gulp for asset management as they are much more powerful and better suited for this.

**Comment by browner12** [comment]
would you mind adding a note to the readme saying this project is no longer maintained? i also came across this repo when searching for some minify help.

**Comment by ericlbarnes** [comment]
Done!

**Comment by browner12** [comment]
thanks. appreciate it!
